
import { CategoryInfo } from '@/types';

// Mock categories data
export const categories: Record<string, CategoryInfo> = {
  documentos_cnpj: {
    id: 'documentos_cnpj',
    title: 'Documentos CNPJ',
    description: 'Acesse seus documentos de CNPJ e informações cadastrais',
    icon: 'file',
  },
  guia_impostos: {
    id: 'guia_impostos',
    title: 'Guia de Impostos',
    description: 'Consulte suas guias de impostos e obrigações fiscais',
    icon: 'file-text',
  },
  folha_pagamento: {
    id: 'folha_pagamento',
    title: 'Folha de Pagamento',
    description: 'Acesse os documentos relacionados à folha de pagamento',
    icon: 'users',
  },
  certidoes: {
    id: 'certidoes',
    title: 'Certidões',
    description: 'Visualize suas certidões e documentos de regularidade',
    icon: 'check-circle',
  },
  mensalidade: {
    id: 'mensalidade',
    title: 'Mensalidade',
    description: 'Acompanhe suas mensalidades e pagamentos',
    icon: 'dollar-sign',
  },
  outras_solicitacoes: {
    id: 'outras_solicitacoes',
    title: 'Outras Solicitações',
    description: 'Faça solicitações adicionais para o escritório',
    icon: 'mail-question',
  },
  outros_documentos: {
    id: 'outros_documentos',
    title: 'Outros Documentos',
    description: 'Acesse documentos variados e importantes',
    icon: 'files',
  },
  sugestao_melhorias: {
    id: 'sugestao_melhorias',
    title: 'Sugestão de Melhorias',
    description: 'Envie sugestões para melhorar nosso portal',
    icon: 'message-circle',
  },
  // Admin categories - now linking directly to admin pages
  gerenciamento_usuarios: {
    id: 'gerenciamento_usuarios',
    title: 'Gerenciamento de Usuários',
    description: 'Administre as contas e permissões dos usuários do sistema',
    icon: 'users',
  },
  gerenciamento_documentos: {
    id: 'gerenciamento_documentos',
    title: 'Gerenciamento de Documentos',
    description: 'Administre os documentos disponíveis no sistema',
    icon: 'file-text',
  },
  gerenciamento_mensalidades: {
    id: 'gerenciamento_mensalidades',
    title: 'Gerenciamento de Mensalidades',
    description: 'Administre as mensalidades e pagamentos dos clientes',
    icon: 'circle-dollar-sign',
  },
  simples_nacional: {
    id: 'simples_nacional',
    title: 'Simples Nacional',
    description: 'Documentos relacionados ao Simples Nacional',
    icon: 'calculator',
    parentId: 'guia_impostos',
  },
  lucro_presumido: {
    id: 'lucro_presumido',
    title: 'Lucro Presumido',
    description: 'Documentos de tributação pelo Lucro Presumido',
    icon: 'briefcase',
    parentId: 'guia_impostos',
  },
  lucro_real: {
    id: 'lucro_real',
    title: 'Lucro Real',
    description: 'Documentos de tributação pelo Lucro Real',
    icon: 'landmark',
    parentId: 'guia_impostos',
  },
  das_simples: {
    id: 'das_simples',
    title: 'DAS - Simples Nacional',
    description: 'Documento de Arrecadação do Simples Nacional',
    icon: 'file-digit',
    parentId: 'simples_nacional',
  },
  difal: {
    id: 'difal',
    title: 'DIFAL',
    description: 'Diferencial de Alíquota',
    icon: 'calculator',
    parentId: 'simples_nacional',
  },
  guia_inss: {
    id: 'guia_inss',
    title: 'Guia INSS',
    description: 'Guias de recolhimento do INSS',
    icon: 'file-check',
    parentId: 'folha_pagamento',
  },
  guia_fgts: {
    id: 'guia_fgts',
    title: 'Guia FGTS',
    description: 'Guias de recolhimento do FGTS',
    icon: 'file-check',
    parentId: 'folha_pagamento',
  },
  ferias: {
    id: 'ferias',
    title: 'Férias',
    description: 'Documentos relacionados a férias',
    icon: 'calendar',
    parentId: 'folha_pagamento',
  },
  holerite: {
    id: 'holerite',
    title: 'Holerites',
    description: 'Contracheques e demonstrativos de pagamento',
    icon: 'receipt',
    parentId: 'folha_pagamento',
  },
  parcelamentos: {
    id: 'parcelamentos',
    title: 'Parcelamentos',
    description: 'Documentos de parcelamentos tributários',
    icon: 'credit-card',
    parentId: 'guia_impostos',
  },
  federal: {
    id: 'federal',
    title: 'Federal',
    description: 'Parcelamentos de tributos federais',
    icon: 'building',
    parentId: 'parcelamentos',
  },
  estadual: {
    id: 'estadual',
    title: 'Estadual',
    description: 'Parcelamentos de tributos estaduais',
    icon: 'library-big',
    parentId: 'parcelamentos',
  },
  cnd_federal: {
    id: 'cnd_federal',
    title: 'CND Federal',
    description: 'Certidão Negativa de Débitos Federais',
    icon: 'badge-check',
    parentId: 'certidoes',
  },
  cnd_estadual: {
    id: 'cnd_estadual',
    title: 'CND Estadual',
    description: 'Certidão Negativa de Débitos Estaduais',
    icon: 'badge-check',
    parentId: 'certidoes',
  },
  cnd_municipal: {
    id: 'cnd_municipal',
    title: 'CND Municipal',
    description: 'Certidão Negativa de Débitos Municipais',
    icon: 'badge-check',
    parentId: 'certidoes',
  },
  cnd_trabalhista: {
    id: 'cnd_trabalhista',
    title: 'CND Trabalhista',
    description: 'Certidão Negativa de Débitos Trabalhistas',
    icon: 'badge-check',
    parentId: 'certidoes',
  },
  imposto_renda: {
    id: 'imposto_renda',
    title: 'Imposto de Renda',
    description: 'Documentos relacionados à declaração de imposto de renda',
    icon: 'receipt',
    parentId: 'outros_documentos',
  },
  documentos_pessoais: {
    id: 'documentos_pessoais',
    title: 'Documentos Pessoais',
    description: 'Documentos de identificação e outros documentos pessoais',
    icon: 'id-card',
    parentId: 'outros_documentos',
  },
  outros_documentos_sub: {
    id: 'outros_documentos_sub',
    title: 'Outros Documentos',
    description: 'Documentos diversos e informações adicionais',
    icon: 'folder',
    parentId: 'outros_documentos',
  },
  cartao_cnpj: {
    id: 'cartao_cnpj',
    title: 'Cartão CNPJ',
    description: 'Comprovante de Inscrição e Situação Cadastral',
    icon: 'credit-card',
    parentId: 'documentos_cnpj',
  },
  contrato_social: {
    id: 'contrato_social',
    title: 'Contrato Social',
    description: 'Documento de constituição e alterações da empresa',
    icon: 'file-text',
    parentId: 'documentos_cnpj',
  },
  inscricao_estadual: {
    id: 'inscricao_estadual',
    title: 'Inscrição Estadual',
    description: 'Documento de registro estadual da empresa',
    icon: 'file-text',
    parentId: 'documentos_cnpj',
  },
};
